version: '3'


networks:
  internal:


volumes:
  rabbitmq-data:
  db-storage-v1:


services:
  
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
    networks:
      - internal
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    restart: unless-stopped


  mongodb:
    image: mongo:latest
    networks: 
      - internal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - db-storage-v1:/data/db
    restart: unless-stopped


  posts:
    build: 
      context: .
      dockerfile: ./Dockerfile.prod
    networks:
      - internal
    ports:
      - 7000:1000
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - MONGODB_USER=${MONGODB_USERNAME}
      - MONGODB_PASS=${MONGODB_PASSWORD}
    depends_on:
      - mongodb
    restart: unless-stopped


