version: "3.7"

volumes:
  rabbitmq-data:
  posts-db-data:

networks:
  rabbit-network:
  posts-network:

services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15673:15672
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev
    networks:
      - rabbit-network
    restart: unless-stopped

  ## Posts ##
  posts:
    build: .
    environment:
      - TZ=Europe/Copenhagen
      - MONGO_CONN_URI=mongodb://mongo:27017/?readPreference=primary&ssl=false
      - RABBITMQ_CONN_URI=amqp://dev:dev@rabbitmq:5672/
      - JWT_HMAC_SECRET=secret
    networks:
      - rabbit-network
      - posts-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    volumes:
      - posts-db-data:/data/db
      - ../.mongo/db-init:/docker-entrypoint-initdb.d
    networks:
      - posts-network
    restart: unless-stopped
    ## End of Posts ##
