kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: posts-v1-deployment
spec:
  # 1. How many copies of each pod do we want?
  replicas: 1

  # 2. How do want to update the pods?
  strategy: Recreate

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      deploy: posts-v1

  # This template field is a regular pod configuration
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: posts-v1
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
