version: "3.7"

volumes:
  db-storage:
  rabbitmq-data:

services:
  vscode:
    image: qmcgaw/godevcontainer
    volumes:
      - ../src:/workspace
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Copenhagen
      - MONGO_CONN_URI=mongodb://mongo:27017/?readPreference=primary&ssl=false
      - MONGO_SERVICE_DB=posts-db
      - RABBITMQ_CONN_URI=amqp://guest:guest@rabbitmq:5672/
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: zsh -c "while sleep 1000; do :; done"

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    restart: unless-stopped

  mongo:
    image: mongo:latest
    volumes:
      - db-storage:/data/db
      - ../.mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=posts
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
