version: "3.7"

volumes:
  posts-db-data:
  rabbitmq-data:
  auth-db-data:

networks:
  rabbit-network:
  auth-network:
  posts-network:


services:
  vscode:
    image: qmcgaw/godevcontainer
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Copenhagen
      - MONGO_CONN_URI=mongodb://mongo:27017/?readPreference=primary&ssl=false
      - MONGO_SERVICE_DB=posts-db
      - RABBITMQ_CONN_URI=amqp://dev:dev@rabbitmq:5672/
      - JWT_HMAC_SECRET=secret
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    networks:
      - rabbit-network
      - auth-network
      - posts-network
    entrypoint: zsh -c "while sleep 1000; do :; done"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - posts-network
    restart: always

  rabbitmq:
    extends:
      file: ../docker-compose.yml
      service: rabbitmq

  posts:
    extends:
      file: ../docker-compose.yml
      service: posts

  mongo:
    extends:
      file: ../docker-compose.yml
      service: mongo

  authentication:
    extends:
      file: ../docker-compose.yml
      service: authentication

  mysql:
    extends:
      file: ../docker-compose.yml
      service: mysql
