name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  image_build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build .
