name: Publish Docker image
on:
  push:
    tags:
      - v*

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true

      - name: Push to Docker Hub as latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: imagehostmad/posts:latest

      - name: Push to Docker Hub with tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: imagehostmad/posts:{tag}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}